import Head from 'next/head'
import Navbar from '@/components/Navbar';
import {Grid, Box} from '@mui/material';
import HelperBox from '@/components/HelperBox';
import Categories from '@/components/Categories';
import SpeechForm from '@/components/SpeechForm';


export default function Home() {
  return (
    <>
      <Head>
        <title>ChatterBox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box sx={{ flexGrow: 1 }}>
        <Grid container spacing={2} style={{width: '100%', margin:'auto'}}>
                <Grid item xs={12}>
                  <Navbar />
                </Grid>
                <Grid item xs={4}>
                  <HelperBox/>
                </Grid>
                <Grid item xs={8}>
                  <div style={{height: '55vh'}}>
                    <SpeechForm/>
                  </div>
                </Grid>
                <Grid item xs={12}>
                  <Categories />
                </Grid>
        </Grid>
      </Box>
      
    </>
  )
}
